drop table if exists BOOK;
CREATE TABLE BOOK(ID NUMBER(20),NAME VARCHAR2(20),AUTHOR VARCHAR2(20),CATEGORY VARCHAR2(20),ReturnDate DATE,primary key);/
INSERT INTO BOOK VALUES (100,'ARTHASASTRA','KAUTILYA','HISTORY','01-FEB-92');
/
INSERT INTO BOOK VALUES (101,'ANANDMATH','BANKIMCHANDRA ','HISTORY','16-APR-94');
/
INSERT INTO BOOK VALUES (102,'UNBREAKABLE','MARY KO','AUTOBIOGRAPHY','22-SEP-96');
/
INSERT INTO BOOK VALUES (103,'AUDOCITY OF HOPE','BARACK OBAMA','HISTORY','09-FEB-99');
/
INSERT INTO BOOK VALUES (104,'WINGS OF FIRE','ABDUL KALAM','HISTORY','01-JUL-92');
/
INSERT INTO BOOK VALUES (105,'MY EXPERIMENTS WIT','GANDHI','AUTO BIOGRAPHY','12-FEB-94');   
/
INSERT INTO BOOK VALUES (106,'A BETTER INDIA','NARAYAN MURTHY','HISTORY','01-APR-92');
/
INSERT INTO BOOK VALUES (107,'A PASSAGE TO INDIA','EM FOSTER','FRICTION','22-FEB-96');
/
INSERT INTO BOOK VALUES (108,'DEATH OF A CITY','AMRITA PREETAM','HISTORY','12-SEP-92');
/
INSERT INTO BOOK VALUES (109,'A SUITABLE BOY','VIKRAM SETH','FRICTION','07-APR-99');
/