Begin
   execute immediate 'Drop table BOOK';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE BOOK(
  ID NUMBER(20),
  NAME VARCHAR2(20),
  AUTHOR VARCHAR2(20),
  CATEGORY VARCHAR2(20),
  Return_Date DATE,
  primary key(ID)
);
INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (100,'ARTHASASTRA','KAUTILYA','HISTORY','01-FEB-92');

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES(101,'ANANDMATH','BANKIMCHANDRA ','HISTORY','16-APR-94');

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (102,'UNBREAKABLE','MARY KO','AUTOBIOGRAPHY','22-SEP-96');

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (103,'AUDOCITY OF HOPE','BARACK OBAMA','HISTORY','09-FEB-99');

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (104,'WINGS OF FIRE','ABDUL KALAM','HISTORY','01-JUL-22');

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (105,'MY EXPERIMENTS WIT','GANDHI','AUTO BIOGRAPHY','12-FEB-22');   

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (106,'A BETTER INDIA','NARAYAN MURTHY','HISTORY','01-APR-92');

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (107,'A PASSAGE TO INDIA','EM FOSTER','FRICTION','22-FEB-23');

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (108,'DEATH OF A CITY','AMRITA PREETAM','HISTORY','12-SEP-23');

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (109,'A SUITABLE BOY','VIKRAM SETH','FRICTION','07-APR-99');

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (122,'newbook','KAUTILYA','HISTORY','27-FEB-2022');

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (124,'newbook','KAUTILYA','HISTORY','27-FEB-2023');