Begin
   execute immediate 'Drop table Book';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE BOOK(
  ID NUMBER(20),
  NAME VARCHAR2(40),
  AUTHOR VARCHAR2(40),
  CATEGORY VARCHAR2(40),
  Return_Date DATE,
  primary key(ID)
);
INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (100,'ARTHASASTRA','KAUTILYA','HISTORY','01-FEB-2024');

 

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES(101,'ANANDMATH','BANKIMCHANDRA ','HISTORY','16-APR-2021');

 

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (102,'UNBREAKABLE','MARY KO','AUTOBIOGRAPHY','22-SEP-2021');

 

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (103,'AUDOCITY OF HOPE','BARACK OBAMA','HISTORY','09-FEB-2020');

 

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (104,'WINGS OF FIRE','ABDUL KALAM','HISTORY','01-JUL-2021');

 

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (105,'MY EXPERIMENTS WIT','GANDHI','AUTO BIOGRAPHY','12-FEB-2021');   

 

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (106,'A BETTER INDIA','NARAYAN MURTHY','HISTORY','01-APR-2022');

 

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (107,'A PASSAGE TO INDIA','EM FOSTER','FRICTION','22-FEB-2023');

 

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (108,'DEATH OF A CITY','AMRITA PREETAM','HISTORY','12-SEP-23');

 

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (109,'A SUITABLE BOY','VIKRAM SETH','FRICTION','07-APR-2022');

 

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (110,'THE GUNS OF AUGUST','KAUTILYA','HISTORY','27-FEB-2022');

 

INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (111,'THE LAST MUGHAL','WILLIAM DALRYMPLE','HISTORY','27-FEB-2022');



INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (112,'IRISH REVEL','EDNA BRIEN','ROMANCE','19-SEP-2021');


INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (113,'THRONAPPLE','RUTH RENDELL','CRIME','10-DEC-2021');




INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (114,'POWER SYSTEMS','J.B.GUPTHA','ELECTRICAL','29-MAR-2021');



INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (115,'ELECTRICAL MACHINERY','P.S.BIMBHRA','ELECTRICAL','01-NOV-2022');



INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (116,'POWER ELECTRONICS','P.S.BIMBHRA','ELECTRICAL','03-OCT-2021');


INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (117,'CONCRETE STRUCTURES','J.N. BANDYOPADHYAY','CIVIL','01-MAY-2022');



INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (118,'HISTORY OF TIME','STEPHEN HAWKING','FRICTION','16-JAN-2023');



INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (119,'MY INVENTIONS','NIKOLA TESLA','AUTO BIOGRAPHY','20-OCT-2022');



INSERT INTO BOOK(ID,NAME,AUTHOR,CATEGORY,Return_Date)
VALUES (120,'AN AUTOBIOGRAPHY','JAWAHARLAL NEHRU','AUTO BIOGRAPHY','01-AUG-2021');


COMMIT;